# Generated by Django 2.0.7 on 2018-07-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=300)),
                ('price', models.PositiveIntegerField()),
                ('view', models.PositiveIntegerField()),
                ('Start_data', models.DateTimeField(auto_now_add=True, null=True)),
                ('End_data', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
