# Generated by Django 2.0.7 on 2018-07-07 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('city', models.CharField(default='Cairo', max_length=255)),
                ('Name', models.CharField(default='mmmm', max_length=200)),
                ('Code_Num', models.IntegerField(default=0)),
                ('Expiration_date', models.DateTimeField(blank=True, null=True)),
                ('CVC', models.IntegerField(default=0)),
            ],
        ),
    ]
