# Generated by Django 2.0.7 on 2018-07-07 07:50

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userdetails_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='location',
            field=location_field.models.plain.PlainLocationField(default=30.59595661670199, max_length=63),
        ),
    ]
