# Generated by Django 2.0.7 on 2018-07-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20180707_0751'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_price', models.PositiveIntegerField()),
                ('product_name', models.ManyToManyField(to='user.Product')),
                ('user_name', models.ManyToManyField(to='user.UserDetails')),
            ],
        ),
    ]
