# Generated by Django 2.0.7 on 2018-07-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_userorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pro_IMG',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
    ]
