# Generated by Django 2.0.7 on 2018-07-07 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_product_pro_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pro_IMG',
            new_name='product_Image',
        ),
    ]
