# Generated by Django 2.0.7 on 2018-07-07 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20180707_0954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='Name',
            new_name='CCName',
        ),
    ]
