# Generated by Django 2.0.7 on 2018-07-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20180707_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='city',
            field=models.CharField(default='Menofia', max_length=255),
        ),
    ]
